/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:7c710b1ec81d69126c7a631f14a3ca1c:4b6bc17f167bb762063a4341e90dfd93:b48ee326db73369a8bacf61834123587$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class ObjetSalle
	{
		public const string ChefRang = "ChefRang";
		public const string Client = "Client";
		public const string MaitreHotel = "MaitreHotel";
		public const string Salle = "Salle";
		public const string Serveur = "Serveur";
	}
}