/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:8918d5998d00ff1495aaca36fa3ab082:5582fc458b72499679741b331d6204ef:84e9cef601c62714f69a02a7f4884e48$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class ObjetCuisine
	{
		public const string ChefCuisinier = "ChefCuisinier";
		public const string Cuisine = "Cuisine";
		public const string Cuisinier = "Cuisinier";
		public const string Plongeur = "Plongeur";
	}
}