CREATE TABLE Demande_client (ID_commandes int NOT NULL, TableID_Table int NOT NULL, PRIMARY KEY (ID_commandes));
CREATE TABLE Etape_Recette (ID_Etape int NOT NULL, nom varchar(255) NULL, temps int NULL, Ordre int NULL, RecetteID_Recette int NOT NULL, PRIMARY KEY (ID_Etape));
CREATE TABLE Ingredient (ID_Ingredient int NOT NULL, nom varchar(255) NULL, quantité int NULL, Stock_ingrédientID_Stock int NOT NULL, PRIMARY KEY (ID_Ingredient));
CREATE TABLE Ingredient_Etape_Recette (IngredientID_Ingredient int NOT NULL, Etape_RecetteID_Etape int NOT NULL, PRIMARY KEY (IngredientID_Ingredient, Etape_RecetteID_Etape));
CREATE TABLE Matériel_cuisine (ID_Materiel_cuisine int NOT NULL, nom varchar(255) NULL, quantité int NULL, Quantité_propre int NULL, PRIMARY KEY (ID_Materiel_cuisine));
CREATE TABLE Matériel_Etape_recette (Matériel_cuisineID_Materiel_cuisine int NOT NULL, Etape_RecetteID_Etape int NOT NULL, PRIMARY KEY (Matériel_cuisineID_Materiel_cuisine, Etape_RecetteID_Etape));
CREATE TABLE Matériel_salle (ID_Materiel_salle int NOT NULL, Nom varchar(255) NULL, quantité int NULL, Quantité_propre int NULL, PRIMARY KEY (ID_Materiel_salle));
CREATE TABLE Matériel_Table (Matériel_salleID_Materiel_salle int NOT NULL, PlaceID_Table int NOT NULL, PRIMARY KEY (Matériel_salleID_Materiel_salle, PlaceID_Table));
CREATE TABLE Place (ID_Table int NOT NULL, Etat_occupe bit NULL, type varchar(255) NULL, Etat_sale bit NULL, x int NULL, y int NULL, PRIMARY KEY (ID_Table));
CREATE TABLE Recette (ID_Recette int NOT NULL, Nom varchar(255) NULL, [Temps prépa] int NULL, [Nombre de personne] int NULL, type int NULL, Demande_clientID_commandes int NOT NULL, PRIMARY KEY (ID_Recette));
CREATE TABLE Stock_ingrédient (ID_Stock int NOT NULL, Nom varchar(255) NULL, quantité int NULL, état int NULL, [date livraison] date NULL, PRIMARY KEY (ID_Stock));
ALTER TABLE Ingredient_Etape_Recette ADD CONSTRAINT FKIngredient829388 FOREIGN KEY (Etape_RecetteID_Etape) REFERENCES Etape_Recette (ID_Etape);
ALTER TABLE Matériel_Etape_recette ADD CONSTRAINT FKMatériel_E519515 FOREIGN KEY (Matériel_cuisineID_Materiel_cuisine) REFERENCES Matériel_cuisine (ID_Materiel_cuisine);
ALTER TABLE Matériel_Etape_recette ADD CONSTRAINT FKMatériel_E639671 FOREIGN KEY (Etape_RecetteID_Etape) REFERENCES Etape_Recette (ID_Etape);
ALTER TABLE Matériel_Table ADD CONSTRAINT FKMatériel_T959896 FOREIGN KEY (Matériel_salleID_Materiel_salle) REFERENCES Matériel_salle (ID_Materiel_salle);
ALTER TABLE Matériel_Table ADD CONSTRAINT FKMatériel_T658824 FOREIGN KEY (PlaceID_Table) REFERENCES Place (ID_Table);
ALTER TABLE Demande_client ADD CONSTRAINT commander FOREIGN KEY (TableID_Table) REFERENCES Place (ID_Table);
ALTER TABLE Recette ADD CONSTRAINT comporter FOREIGN KEY (Demande_clientID_commandes) REFERENCES Demande_client (ID_commandes);
ALTER TABLE Ingredient_Etape_Recette ADD CONSTRAINT Contenue FOREIGN KEY (IngredientID_Ingredient) REFERENCES Ingredient (ID_Ingredient);
ALTER TABLE Etape_Recette ADD CONSTRAINT [Se situe] FOREIGN KEY (RecetteID_Recette) REFERENCES Recette (ID_Recette);
ALTER TABLE Ingredient ADD CONSTRAINT Stocker FOREIGN KEY (Stock_ingrédientID_Stock) REFERENCES Stock_ingrédient (ID_Stock);

